### ISSUE TITLE
Adapter openfisca-france-pension à GitHub

### ISSUE THREAD

**Issue by sandcha** [openfisca/openfisca-france-pension#2]
Merci @benjello pour l'ajout de ce nouveau dépôt, qui plus est, sur un thème aussi majeur ❤️ 

Ce code était hébergé sur une forge GitLab, quelques fichiers sont donc à adapter aux syntaxes GitHub. 
Par ailleurs, cela peut s'étendre à l'adoption de quelques éléments facilitant la contribution comme les templates de pull requests...

Cette issue propose donc de lister les premiers éléments à mettre en oeuvre pour le bon accueil de se dépôt sur https://github.com/openfisca/ 😁 et d'en débattre ici le cas échéant. cc @benoit-cty

**Comment by sandcha** [comment]
- [ ] Pour aligner la technologie d'intégration continue (CI) à ce qu'il y a sur les autres principaux dépôts de l'organisation, la migrer `.gitlab/` et `.circleci/` vers un workflow GitHub Action `.github/` 
  → Donc, en ne conservant que `.github/`

**Comment by sandcha** [comment]
- [ ] Pour faciliter la réutilisation et la découvrabilité du dépôt, inclure à la CI, la publication sur PyPi de la librairie ?

**Comment by sandcha** [comment]
- [ ] Pour faciliter la contribution, ajouter les templates d'issue et de pull request sur le modèle de [ce que l'on a pour openfisca-france](https://github.com/openfisca/openfisca-france/tree/master/.github)

**Comment by sandcha** [comment]
- [ ] Pour faciliter la contribution et conserver la lisibilité des modifications passées, activer l'emploi du CHANGELOG aujourd'hui vide ? 
  → Donc, activer en CI la nécessité de mettre à jour le CHANGELOG.
  → La mise en oeuvre du template de pull request pourra aider les usagers à la structuration de leurs descriptions de changements.

**Comment by sandcha** [comment]
- [ ] Pour faciliter la découvrabilité de l'historique du dépôt et aider à la résolution potentielle future de bugs, ajouter un lien vers la forge GitLab d'origine au bas du CHANGELOG
  →  Ajouter un lien vers le répertoire de merge requests sur GitLab. Voire, copier-coller la séquence des merge requests même s'il n'y a pas eu de versionnement ?

**Comment by sandcha** [comment]
- [ ] Pour faciliter la contribution, traduire le [fichier CONTRIBUTING.md](https://github.com/openfisca/openfisca-france-pension/blob/ec89d810057aad03a28a69c75832a61eea60b9a7/CONTRIBUTING.md) dans la langue de référence de la législation modélisée/du dépôt [comme on l'indique dans la documentation](https://openfisca.org/doc/contribute/language.html#country-specific-repositories)
  → Donc en français ? 🇫🇷

**Comment by sandcha** [comment]
- [ ] Pour faciliter la découvrabilité du dépôt, la contribution et la gestion des accès des contributeurs, ajouter le dépôt `openfisca-france-pension` a minima aux teams [France-Maintainers](https://github.com/orgs/openfisca/teams/france-maintainers) et [France-Contrib](https://github.com/orgs/openfisca/teams/france-contrib)
  → En complément d'autres équipes vous viennent-elles à l'esprit ?

**Comment by benjello** [comment]
> * [x]  Pour faciliter la découvrabilité du dépôt, la contribution et la gestion des accès des contributeurs, ajouter le dépôt `openfisca-france-pension` a minima aux teams [France-Maintainers](https://github.com/orgs/openfisca/teams/france-maintainers) et [France-Contrib](https://github.com/orgs/openfisca/teams/france-contrib)
>       → En complément d'autres équipes vous viennent-elles à l'esprit ?

J'ai rajouté aussi contrib-IPP
